// Code generated by schema-generate. DO NOT EDIT.

package v1beta2

import (
    "bytes"
    "encoding/json"
    "errors"
)

// AccessToken Link to Kubernetes Secret containing the access token which was obtained from the authorization server.
type AccessToken struct {

  // The key under which the secret value is stored in the Kubernetes Secret.
  Key string `json:"key"`

  // The name of the Kubernetes Secret containing the secret value.
  SecretName string `json:"secretName"`
}

// Affinity The pod's affinity rules.
type Affinity struct {
  NodeAffinity *NodeAffinity `json:"nodeAffinity,omitempty"`
  PodAffinity *PodAffinity `json:"podAffinity,omitempty"`
  PodAntiAffinity *PodAntiAffinity `json:"podAntiAffinity,omitempty"`
}

// Annotations Annotations added to the Kubernetes resource.
type Annotations struct {
}

// ApiService Template for Kafka Connect API `Service`.
type ApiService struct {

  // Specifies the IP Families used by the service. Available options are `IPv4` and `IPv6`. If unspecified, Kubernetes will choose the default value based on the `ipFamilyPolicy` setting.
  IpFamilies []string `json:"ipFamilies,omitempty"`

  // Specifies the IP Family Policy used by the service. Available options are `SingleStack`, `PreferDualStack` and `RequireDualStack`. `SingleStack` is for a single IP family. `PreferDualStack` is for two IP families on dual-stack configured clusters or a single IP family on single-stack clusters. `RequireDualStack` fails unless there are two IP families on dual-stack configured clusters. If unspecified, Kubernetes will choose the default value based on the service type.
  IpFamilyPolicy string `json:"ipFamilyPolicy,omitempty"`

  // Metadata applied to the resource.
  Metadata *Metadata `json:"metadata,omitempty"`
}

// Authentication Authentication configuration for connecting to the JMX port.
type Authentication struct {

  // Authentication type. Currently the only supported types are `password`.`password` type creates a username and protected port with no TLS.
  Type string `json:"type"`
}

// AutoRestart Automatic restart of connector and tasks configuration.
type AutoRestart struct {

  // Whether automatic restart for failed connectors and tasks should be enabled or disabled.
  Enabled bool `json:"enabled,omitempty"`
}

// AutoRestartStatusesItems 
type AutoRestartStatusesItems struct {

  // The name of the connector being restarted.
  ConnectorName string `json:"connectorName,omitempty"`

  // The number of times the connector or task is restarted.
  Count int `json:"count,omitempty"`

  // The last time the automatic restart was attempted. The required format is 'yyyy-MM-ddTHH:mm:ssZ' in the UTC time zone.
  LastRestartTimestamp string `json:"lastRestartTimestamp,omitempty"`
}

// BuildConfig Template for the Kafka Connect BuildConfig used to build new container images. The BuildConfig is used only on OpenShift.
type BuildConfig struct {

  // Metadata to apply to the `PodDisruptionBudgetTemplate` resource.
  Metadata *Metadata `json:"metadata,omitempty"`

  // Container Registry Secret with the credentials for pulling the base image.
  PullSecret string `json:"pullSecret,omitempty"`
}

// BuildContainer Template for the Kafka Connect Build container. The build container is used only on Kubernetes.
type BuildContainer struct {

  // Environment variables which should be applied to the container.
  Env []*EnvItems `json:"env,omitempty"`

  // Security context for the container.
  SecurityContext *SecurityContext `json:"securityContext,omitempty"`
}

// BuildPod Template for Kafka Connect Build `Pods`. The build pod is used only on Kubernetes.
type BuildPod struct {

  // The pod's affinity rules.
  Affinity *Affinity `json:"affinity,omitempty"`

  // Indicates whether information about services should be injected into Pod's environment variables.
  EnableServiceLinks bool `json:"enableServiceLinks,omitempty"`

  // The pod's HostAliases. HostAliases is an optional list of hosts and IPs that will be injected into the Pod's hosts file if specified.
  HostAliases []*HostAliasesItems `json:"hostAliases,omitempty"`

  // List of references to secrets in the same namespace to use for pulling any of the images used by this Pod. When the `STRIMZI_IMAGE_PULL_SECRETS` environment variable in Cluster Operator and the `imagePullSecrets` option are specified, only the `imagePullSecrets` variable is used and the `STRIMZI_IMAGE_PULL_SECRETS` variable is ignored.
  ImagePullSecrets []*ImagePullSecretsItems `json:"imagePullSecrets,omitempty"`

  // Metadata applied to the resource.
  Metadata *Metadata `json:"metadata,omitempty"`

  // The name of the priority class used to assign priority to the pods. For more information about priority classes, see {K8sPriorityClass}.
  PriorityClassName string `json:"priorityClassName,omitempty"`

  // The name of the scheduler used to dispatch this `Pod`. If not specified, the default scheduler will be used.
  SchedulerName string `json:"schedulerName,omitempty"`

  // Configures pod-level security attributes and common container settings.
  SecurityContext *SecurityContext `json:"securityContext,omitempty"`

  // The grace period is the duration in seconds after the processes running in the pod are sent a termination signal, and the time when the processes are forcibly halted with a kill signal. Set this value to longer than the expected cleanup time for your process. Value must be a non-negative integer. A zero value indicates delete immediately. You might need to increase the grace period for very large Kafka clusters, so that the Kafka brokers have enough time to transfer their work to another broker before they are terminated. Defaults to 30 seconds.
  TerminationGracePeriodSeconds int `json:"terminationGracePeriodSeconds,omitempty"`

  // Defines the total amount (for example `1Gi`) of local storage required for temporary EmptyDir volume (`/tmp`). Default value is `5Mi`.
  TmpDirSizeLimit string `json:"tmpDirSizeLimit,omitempty"`

  // The pod's tolerations.
  Tolerations []*TolerationsItems `json:"tolerations,omitempty"`

  // The pod's topology spread constraints.
  TopologySpreadConstraints []*TopologySpreadConstraintsItems `json:"topologySpreadConstraints,omitempty"`
}

// BuildServiceAccount Template for the Kafka Connect Build service account.
type BuildServiceAccount struct {

  // Metadata applied to the resource.
  Metadata *Metadata `json:"metadata,omitempty"`
}

// Capabilities 
type Capabilities struct {
  Add []string `json:"add,omitempty"`
  Drop []string `json:"drop,omitempty"`
}

// CertificateAndKey Reference to the `Secret` which holds the certificate and private key pair.
type CertificateAndKey struct {

  // The name of the file certificate in the Secret.
  Certificate string `json:"certificate"`

  // The name of the private key in the Secret.
  Key string `json:"key"`

  // The name of the Secret containing the certificate.
  SecretName string `json:"secretName"`
}

// CheckpointConnector The specification of the Kafka MirrorMaker 2 checkpoint connector.
type CheckpointConnector struct {

  // Automatic restart of connector and tasks configuration.
  AutoRestart *AutoRestart `json:"autoRestart,omitempty"`

  // The Kafka Connector configuration. The following properties cannot be set: connector.class, tasks.max.
  Config *Config `json:"config,omitempty"`

  // Whether the connector should be paused. Defaults to false.
  Pause bool `json:"pause,omitempty"`

  // The maximum number of tasks for the Kafka Connector.
  TasksMax int `json:"tasksMax,omitempty"`
}

// ClaimsItems 
type ClaimsItems struct {
  Name string `json:"name,omitempty"`
}

// ClientSecret Link to Kubernetes Secret containing the OAuth client secret which the Kafka client can use to authenticate against the OAuth server and use the token endpoint URI.
type ClientSecret struct {

  // The key under which the secret value is stored in the Kubernetes Secret.
  Key string `json:"key"`

  // The name of the Kubernetes Secret containing the secret value.
  SecretName string `json:"secretName"`
}

// ClusterRoleBinding Template for the Kafka Connect ClusterRoleBinding.
type ClusterRoleBinding struct {

  // Metadata applied to the resource.
  Metadata *Metadata `json:"metadata,omitempty"`
}

// ClustersItems 
type ClustersItems struct {

  // Alias used to reference the Kafka cluster.
  Alias string `json:"alias"`

  // Authentication configuration for connecting to the cluster.
  Authentication *Authentication `json:"authentication,omitempty"`

  // A comma-separated list of `host:port` pairs for establishing the connection to the Kafka cluster.
  BootstrapServers string `json:"bootstrapServers"`

  // The MirrorMaker 2 cluster config. Properties with the following prefixes cannot be set: ssl., sasl., security., listeners, plugin.path, rest., bootstrap.servers, consumer.interceptor.classes, producer.interceptor.classes (with the exception of: ssl.endpoint.identification.algorithm, ssl.cipher.suites, ssl.protocol, ssl.enabled.protocols).
  Config *Config `json:"config,omitempty"`

  // TLS configuration for connecting MirrorMaker 2 connectors to a cluster.
  Tls *Tls `json:"tls,omitempty"`
}

// ConditionsItems 
type ConditionsItems struct {

  // Last time the condition of a type changed from one status to another. The required format is 'yyyy-MM-ddTHH:mm:ssZ', in the UTC time zone.
  LastTransitionTime string `json:"lastTransitionTime,omitempty"`

  // Human-readable message indicating details about the condition's last transition.
  Message string `json:"message,omitempty"`

  // The reason for the condition's last transition (a single word in CamelCase).
  Reason string `json:"reason,omitempty"`

  // The status of the condition, either True, False or Unknown.
  Status string `json:"status,omitempty"`

  // The unique identifier of a condition, used to distinguish between other conditions in the resource.
  Type string `json:"type,omitempty"`
}

// Config The MirrorMaker 2 cluster config. Properties with the following prefixes cannot be set: ssl., sasl., security., listeners, plugin.path, rest., bootstrap.servers, consumer.interceptor.classes, producer.interceptor.classes (with the exception of: ssl.endpoint.identification.algorithm, ssl.cipher.suites, ssl.protocol, ssl.enabled.protocols).
type Config struct {
}

// ConfigMap Reference to a key in a ConfigMap. Exactly one Secret or ConfigMap has to be specified.
type ConfigMap struct {
  DefaultMode int `json:"defaultMode,omitempty"`
  Items []*ItemsItems `json:"items,omitempty"`
  Name string `json:"name,omitempty"`
  Optional bool `json:"optional,omitempty"`
}

// ConfigMapKeyRef Reference to a key in a ConfigMap.
type ConfigMapKeyRef struct {
  Key string `json:"key,omitempty"`
  Name string `json:"name,omitempty"`
  Optional bool `json:"optional,omitempty"`
}

// ConnectContainer Template for the Kafka Connect container.
type ConnectContainer struct {

  // Environment variables which should be applied to the container.
  Env []*EnvItems `json:"env,omitempty"`

  // Security context for the container.
  SecurityContext *SecurityContext `json:"securityContext,omitempty"`
}

// ConnectorPluginsItems 
type ConnectorPluginsItems struct {

  // The class of the connector plugin.
  Class string `json:"class,omitempty"`

  // The type of the connector plugin. The available types are `sink` and `source`.
  Type string `json:"type,omitempty"`

  // The version of the connector plugin.
  Version string `json:"version,omitempty"`
}

// ConnectorsItems 
type ConnectorsItems struct {
}

// Deployment Template for Kafka Connect `Deployment`.
type Deployment struct {

  // Pod replacement strategy for deployment configuration changes. Valid values are `RollingUpdate` and `Recreate`. Defaults to `RollingUpdate`.
  DeploymentStrategy string `json:"deploymentStrategy,omitempty"`

  // Metadata applied to the resource.
  Metadata *Metadata `json:"metadata,omitempty"`
}

// EnvItems 
type EnvItems struct {

  // Name of the environment variable which will be passed to the Kafka Connect pods. The name of the environment variable cannot start with `KAFKA_` or `STRIMZI_`.
  Name string `json:"name"`

  // Value of the environment variable which will be passed to the Kafka Connect pods. It can be passed either as a reference to Secret or ConfigMap field. The field has to specify exactly one Secret or ConfigMap.
  ValueFrom *ValueFrom `json:"valueFrom"`
}

// ExternalConfiguration Pass data from Secrets or ConfigMaps to the Kafka Connect pods and use them to configure connectors.
type ExternalConfiguration struct {

  // Makes data from a Secret or ConfigMap available in the Kafka Connect pods as environment variables.
  Env []*EnvItems `json:"env,omitempty"`

  // Makes data from a Secret or ConfigMap available in the Kafka Connect pods as volumes.
  Volumes []*VolumesItems `json:"volumes,omitempty"`
}

// HeadlessService Template for Kafka Connect headless `Service`.
type HeadlessService struct {

  // Specifies the IP Families used by the service. Available options are `IPv4` and `IPv6`. If unspecified, Kubernetes will choose the default value based on the `ipFamilyPolicy` setting.
  IpFamilies []string `json:"ipFamilies,omitempty"`

  // Specifies the IP Family Policy used by the service. Available options are `SingleStack`, `PreferDualStack` and `RequireDualStack`. `SingleStack` is for a single IP family. `PreferDualStack` is for two IP families on dual-stack configured clusters or a single IP family on single-stack clusters. `RequireDualStack` fails unless there are two IP families on dual-stack configured clusters. If unspecified, Kubernetes will choose the default value based on the service type.
  IpFamilyPolicy string `json:"ipFamilyPolicy,omitempty"`

  // Metadata applied to the resource.
  Metadata *Metadata `json:"metadata,omitempty"`
}

// HeartbeatConnector The specification of the Kafka MirrorMaker 2 heartbeat connector.
type HeartbeatConnector struct {

  // Automatic restart of connector and tasks configuration.
  AutoRestart *AutoRestart `json:"autoRestart,omitempty"`

  // The Kafka Connector configuration. The following properties cannot be set: connector.class, tasks.max.
  Config *Config `json:"config,omitempty"`

  // Whether the connector should be paused. Defaults to false.
  Pause bool `json:"pause,omitempty"`

  // The maximum number of tasks for the Kafka Connector.
  TasksMax int `json:"tasksMax,omitempty"`
}

// HostAliasesItems 
type HostAliasesItems struct {
  Hostnames []string `json:"hostnames,omitempty"`
  Ip string `json:"ip,omitempty"`
}

// ImagePullSecretsItems 
type ImagePullSecretsItems struct {
  Name string `json:"name,omitempty"`
}

// InitContainer Template for the Kafka init container.
type InitContainer struct {

  // Environment variables which should be applied to the container.
  Env []*EnvItems `json:"env,omitempty"`

  // Security context for the container.
  SecurityContext *SecurityContext `json:"securityContext,omitempty"`
}

// ItemsItems 
type ItemsItems struct {
  Key string `json:"key,omitempty"`
  Mode int `json:"mode,omitempty"`
  Path string `json:"path,omitempty"`
}

// JavaSystemPropertiesItems 
type JavaSystemPropertiesItems struct {

  // The system property name.
  Name string `json:"name,omitempty"`

  // The system property value.
  Value string `json:"value,omitempty"`
}

// JmxOptions JMX Options.
type JmxOptions struct {

  // Authentication configuration for connecting to the JMX port.
  Authentication *Authentication `json:"authentication,omitempty"`
}

// JmxSecret Template for Secret of the Kafka Connect Cluster JMX authentication.
type JmxSecret struct {

  // Metadata applied to the resource.
  Metadata *Metadata `json:"metadata,omitempty"`
}

// JvmOptions JVM Options for pods.
type JvmOptions struct {

  // Specifies whether the Garbage Collection logging is enabled. The default is false.
  GcLoggingEnabled bool `json:"gcLoggingEnabled,omitempty"`

  // A map of additional system properties which will be passed using the `-D` option to the JVM.
  JavaSystemProperties []*JavaSystemPropertiesItems `json:"javaSystemProperties,omitempty"`

  // A map of -XX options to the JVM.
  XX *XX `json:"-XX,omitempty"`

  // -Xms option to to the JVM.
  Xms string `json:"-Xms,omitempty"`

  // -Xmx option to to the JVM.
  Xmx string `json:"-Xmx,omitempty"`
}

// KafkaMirrorMaker2 
type KafkaMirrorMaker2 struct {

  // The specification of the Kafka MirrorMaker 2 cluster.
  Spec *Spec `json:"spec,omitempty"`

  // The status of the Kafka MirrorMaker 2 cluster.
  Status *Status `json:"status,omitempty"`
}

// LabelSelector 
type LabelSelector struct {
  MatchExpressions []*MatchExpressionsItems `json:"matchExpressions,omitempty"`
  MatchLabels *MatchLabels `json:"matchLabels,omitempty"`
}

// Labels Labels added to the Kubernetes resource.
type Labels struct {
}

// Limits 
type Limits struct {
}

// LivenessProbe Pod liveness checking.
type LivenessProbe struct {

  // Minimum consecutive failures for the probe to be considered failed after having succeeded. Defaults to 3. Minimum value is 1.
  FailureThreshold int `json:"failureThreshold,omitempty"`

  // The initial delay before first the health is first checked. Default to 15 seconds. Minimum value is 0.
  InitialDelaySeconds int `json:"initialDelaySeconds,omitempty"`

  // How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
  PeriodSeconds int `json:"periodSeconds,omitempty"`

  // Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness. Minimum value is 1.
  SuccessThreshold int `json:"successThreshold,omitempty"`

  // The timeout for each attempted health check. Default to 5 seconds. Minimum value is 1.
  TimeoutSeconds int `json:"timeoutSeconds,omitempty"`
}

// Loggers A Map from logger name to logger level.
type Loggers struct {
}

// Logging Logging configuration for Kafka Connect.
type Logging struct {

  // A Map from logger name to logger level.
  Loggers *Loggers `json:"loggers,omitempty"`

  // Logging type, must be either 'inline' or 'external'.
  Type string `json:"type"`

  // `ConfigMap` entry where the logging configuration is stored. 
  ValueFrom *ValueFrom `json:"valueFrom,omitempty"`
}

// MatchExpressionsItems 
type MatchExpressionsItems struct {
  Key string `json:"key,omitempty"`
  Operator string `json:"operator,omitempty"`
  Values []string `json:"values,omitempty"`
}

// MatchFieldsItems 
type MatchFieldsItems struct {
  Key string `json:"key,omitempty"`
  Operator string `json:"operator,omitempty"`
  Values []string `json:"values,omitempty"`
}

// MatchLabels 
type MatchLabels struct {
}

// Metadata Metadata applied to the resource.
type Metadata struct {

  // Annotations added to the Kubernetes resource.
  Annotations *Annotations `json:"annotations,omitempty"`

  // Labels added to the Kubernetes resource.
  Labels *Labels `json:"labels,omitempty"`
}

// MetricsConfig Metrics configuration.
type MetricsConfig struct {

  // Metrics type. Only 'jmxPrometheusExporter' supported currently.
  Type string `json:"type"`

  // ConfigMap entry where the Prometheus JMX Exporter configuration is stored. For details of the structure of this configuration, see the {JMXExporter}.
  ValueFrom *ValueFrom `json:"valueFrom"`
}

// MirrorsItems 
type MirrorsItems struct {

  // The specification of the Kafka MirrorMaker 2 checkpoint connector.
  CheckpointConnector *CheckpointConnector `json:"checkpointConnector,omitempty"`

  // A regular expression matching the consumer groups to exclude from mirroring. Comma-separated lists are also supported.
  GroupsBlacklistPattern string `json:"groupsBlacklistPattern,omitempty"`

  // A regular expression matching the consumer groups to exclude from mirroring. Comma-separated lists are also supported.
  GroupsExcludePattern string `json:"groupsExcludePattern,omitempty"`

  // A regular expression matching the consumer groups to be mirrored. Comma-separated lists are also supported.
  GroupsPattern string `json:"groupsPattern,omitempty"`

  // The specification of the Kafka MirrorMaker 2 heartbeat connector.
  HeartbeatConnector *HeartbeatConnector `json:"heartbeatConnector,omitempty"`

  // The alias of the source cluster used by the Kafka MirrorMaker 2 connectors. The alias must match a cluster in the list at `spec.clusters`.
  SourceCluster string `json:"sourceCluster"`

  // The specification of the Kafka MirrorMaker 2 source connector.
  SourceConnector *SourceConnector `json:"sourceConnector,omitempty"`

  // The alias of the target cluster used by the Kafka MirrorMaker 2 connectors. The alias must match a cluster in the list at `spec.clusters`.
  TargetCluster string `json:"targetCluster"`

  // A regular expression matching the topics to exclude from mirroring. Comma-separated lists are also supported.
  TopicsBlacklistPattern string `json:"topicsBlacklistPattern,omitempty"`

  // A regular expression matching the topics to exclude from mirroring. Comma-separated lists are also supported.
  TopicsExcludePattern string `json:"topicsExcludePattern,omitempty"`

  // A regular expression matching the topics to be mirrored, for example, "topic1\|topic2\|topic3". Comma-separated lists are also supported.
  TopicsPattern string `json:"topicsPattern,omitempty"`
}

// NamespaceSelector 
type NamespaceSelector struct {
  MatchExpressions []*MatchExpressionsItems `json:"matchExpressions,omitempty"`
  MatchLabels *MatchLabels `json:"matchLabels,omitempty"`
}

// NodeAffinity 
type NodeAffinity struct {
  PreferredDuringSchedulingIgnoredDuringExecution []*PreferredDuringSchedulingIgnoredDuringExecutionItems `json:"preferredDuringSchedulingIgnoredDuringExecution,omitempty"`
  RequiredDuringSchedulingIgnoredDuringExecution *RequiredDuringSchedulingIgnoredDuringExecution `json:"requiredDuringSchedulingIgnoredDuringExecution,omitempty"`
}

// NodeSelectorTermsItems 
type NodeSelectorTermsItems struct {
  MatchExpressions []*MatchExpressionsItems `json:"matchExpressions,omitempty"`
  MatchFields []*MatchFieldsItems `json:"matchFields,omitempty"`
}

// PasswordSecret Reference to the `Secret` which holds the password.
type PasswordSecret struct {

  // The name of the key in the Secret under which the password is stored.
  Password string `json:"password"`

  // The name of the Secret containing the password.
  SecretName string `json:"secretName"`
}

// Pod Template for Kafka Connect `Pods`.
type Pod struct {

  // The pod's affinity rules.
  Affinity *Affinity `json:"affinity,omitempty"`

  // Indicates whether information about services should be injected into Pod's environment variables.
  EnableServiceLinks bool `json:"enableServiceLinks,omitempty"`

  // The pod's HostAliases. HostAliases is an optional list of hosts and IPs that will be injected into the Pod's hosts file if specified.
  HostAliases []*HostAliasesItems `json:"hostAliases,omitempty"`

  // List of references to secrets in the same namespace to use for pulling any of the images used by this Pod. When the `STRIMZI_IMAGE_PULL_SECRETS` environment variable in Cluster Operator and the `imagePullSecrets` option are specified, only the `imagePullSecrets` variable is used and the `STRIMZI_IMAGE_PULL_SECRETS` variable is ignored.
  ImagePullSecrets []*ImagePullSecretsItems `json:"imagePullSecrets,omitempty"`

  // Metadata applied to the resource.
  Metadata *Metadata `json:"metadata,omitempty"`

  // The name of the priority class used to assign priority to the pods. For more information about priority classes, see {K8sPriorityClass}.
  PriorityClassName string `json:"priorityClassName,omitempty"`

  // The name of the scheduler used to dispatch this `Pod`. If not specified, the default scheduler will be used.
  SchedulerName string `json:"schedulerName,omitempty"`

  // Configures pod-level security attributes and common container settings.
  SecurityContext *SecurityContext `json:"securityContext,omitempty"`

  // The grace period is the duration in seconds after the processes running in the pod are sent a termination signal, and the time when the processes are forcibly halted with a kill signal. Set this value to longer than the expected cleanup time for your process. Value must be a non-negative integer. A zero value indicates delete immediately. You might need to increase the grace period for very large Kafka clusters, so that the Kafka brokers have enough time to transfer their work to another broker before they are terminated. Defaults to 30 seconds.
  TerminationGracePeriodSeconds int `json:"terminationGracePeriodSeconds,omitempty"`

  // Defines the total amount (for example `1Gi`) of local storage required for temporary EmptyDir volume (`/tmp`). Default value is `5Mi`.
  TmpDirSizeLimit string `json:"tmpDirSizeLimit,omitempty"`

  // The pod's tolerations.
  Tolerations []*TolerationsItems `json:"tolerations,omitempty"`

  // The pod's topology spread constraints.
  TopologySpreadConstraints []*TopologySpreadConstraintsItems `json:"topologySpreadConstraints,omitempty"`
}

// PodAffinity 
type PodAffinity struct {
  PreferredDuringSchedulingIgnoredDuringExecution []*PreferredDuringSchedulingIgnoredDuringExecutionItems `json:"preferredDuringSchedulingIgnoredDuringExecution,omitempty"`
  RequiredDuringSchedulingIgnoredDuringExecution []*RequiredDuringSchedulingIgnoredDuringExecutionItems `json:"requiredDuringSchedulingIgnoredDuringExecution,omitempty"`
}

// PodAffinityTerm 
type PodAffinityTerm struct {
  LabelSelector *LabelSelector `json:"labelSelector,omitempty"`
  NamespaceSelector *NamespaceSelector `json:"namespaceSelector,omitempty"`
  Namespaces []string `json:"namespaces,omitempty"`
  TopologyKey string `json:"topologyKey,omitempty"`
}

// PodAntiAffinity 
type PodAntiAffinity struct {
  PreferredDuringSchedulingIgnoredDuringExecution []*PreferredDuringSchedulingIgnoredDuringExecutionItems `json:"preferredDuringSchedulingIgnoredDuringExecution,omitempty"`
  RequiredDuringSchedulingIgnoredDuringExecution []*RequiredDuringSchedulingIgnoredDuringExecutionItems `json:"requiredDuringSchedulingIgnoredDuringExecution,omitempty"`
}

// PodDisruptionBudget Template for Kafka Connect `PodDisruptionBudget`.
type PodDisruptionBudget struct {

  // Maximum number of unavailable pods to allow automatic Pod eviction. A Pod eviction is allowed when the `maxUnavailable` number of pods or fewer are unavailable after the eviction. Setting this value to 0 prevents all voluntary evictions, so the pods must be evicted manually. Defaults to 1.
  MaxUnavailable int `json:"maxUnavailable,omitempty"`

  // Metadata to apply to the `PodDisruptionBudgetTemplate` resource.
  Metadata *Metadata `json:"metadata,omitempty"`
}

// PodSet Template for Kafka Connect `StrimziPodSet` resource.
type PodSet struct {

  // Metadata applied to the resource.
  Metadata *Metadata `json:"metadata,omitempty"`
}

// Preference 
type Preference struct {
  MatchExpressions []*MatchExpressionsItems `json:"matchExpressions,omitempty"`
  MatchFields []*MatchFieldsItems `json:"matchFields,omitempty"`
}

// PreferredDuringSchedulingIgnoredDuringExecutionItems 
type PreferredDuringSchedulingIgnoredDuringExecutionItems struct {
  PodAffinityTerm *PodAffinityTerm `json:"podAffinityTerm,omitempty"`
  Weight int `json:"weight,omitempty"`
}

// Rack Configuration of the node label which will be used as the `client.rack` consumer configuration.
type Rack struct {

  // A key that matches labels assigned to the Kubernetes cluster nodes. The value of the label is used to set a broker's `broker.rack` config, and the `client.rack` config for Kafka Connect or MirrorMaker 2.
  TopologyKey string `json:"topologyKey"`
}

// ReadinessProbe Pod readiness checking.
type ReadinessProbe struct {

  // Minimum consecutive failures for the probe to be considered failed after having succeeded. Defaults to 3. Minimum value is 1.
  FailureThreshold int `json:"failureThreshold,omitempty"`

  // The initial delay before first the health is first checked. Default to 15 seconds. Minimum value is 0.
  InitialDelaySeconds int `json:"initialDelaySeconds,omitempty"`

  // How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
  PeriodSeconds int `json:"periodSeconds,omitempty"`

  // Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness. Minimum value is 1.
  SuccessThreshold int `json:"successThreshold,omitempty"`

  // The timeout for each attempted health check. Default to 5 seconds. Minimum value is 1.
  TimeoutSeconds int `json:"timeoutSeconds,omitempty"`
}

// RefreshToken Link to Kubernetes Secret containing the refresh token which can be used to obtain access token from the authorization server.
type RefreshToken struct {

  // The key under which the secret value is stored in the Kubernetes Secret.
  Key string `json:"key"`

  // The name of the Kubernetes Secret containing the secret value.
  SecretName string `json:"secretName"`
}

// Requests 
type Requests struct {
}

// RequiredDuringSchedulingIgnoredDuringExecution 
type RequiredDuringSchedulingIgnoredDuringExecution struct {
  NodeSelectorTerms []*NodeSelectorTermsItems `json:"nodeSelectorTerms,omitempty"`
}

// RequiredDuringSchedulingIgnoredDuringExecutionItems 
type RequiredDuringSchedulingIgnoredDuringExecutionItems struct {
  LabelSelector *LabelSelector `json:"labelSelector,omitempty"`
  NamespaceSelector *NamespaceSelector `json:"namespaceSelector,omitempty"`
  Namespaces []string `json:"namespaces,omitempty"`
  TopologyKey string `json:"topologyKey,omitempty"`
}

// Resources The maximum limits for CPU and memory resources and the requested initial resources.
type Resources struct {
  Claims []*ClaimsItems `json:"claims,omitempty"`
  Limits *Limits `json:"limits,omitempty"`
  Requests *Requests `json:"requests,omitempty"`
}

// SeLinuxOptions 
type SeLinuxOptions struct {
  Level string `json:"level,omitempty"`
  Role string `json:"role,omitempty"`
  Type string `json:"type,omitempty"`
  User string `json:"user,omitempty"`
}

// SeccompProfile 
type SeccompProfile struct {
  LocalhostProfile string `json:"localhostProfile,omitempty"`
  Type string `json:"type,omitempty"`
}

// Secret Reference to a key in a Secret. Exactly one Secret or ConfigMap has to be specified.
type Secret struct {
  DefaultMode int `json:"defaultMode,omitempty"`
  Items []*ItemsItems `json:"items,omitempty"`
  Optional bool `json:"optional,omitempty"`
  SecretName string `json:"secretName,omitempty"`
}

// SecretKeyRef Reference to a key in a Secret.
type SecretKeyRef struct {
  Key string `json:"key,omitempty"`
  Name string `json:"name,omitempty"`
  Optional bool `json:"optional,omitempty"`
}

// SecurityContext Configures pod-level security attributes and common container settings.
type SecurityContext struct {
  FsGroup int `json:"fsGroup,omitempty"`
  FsGroupChangePolicy string `json:"fsGroupChangePolicy,omitempty"`
  RunAsGroup int `json:"runAsGroup,omitempty"`
  RunAsNonRoot bool `json:"runAsNonRoot,omitempty"`
  RunAsUser int `json:"runAsUser,omitempty"`
  SeLinuxOptions *SeLinuxOptions `json:"seLinuxOptions,omitempty"`
  SeccompProfile *SeccompProfile `json:"seccompProfile,omitempty"`
  SupplementalGroups []int `json:"supplementalGroups,omitempty"`
  Sysctls []*SysctlsItems `json:"sysctls,omitempty"`
  WindowsOptions *WindowsOptions `json:"windowsOptions,omitempty"`
}

// ServiceAccount Template for the Kafka Connect service account.
type ServiceAccount struct {

  // Metadata applied to the resource.
  Metadata *Metadata `json:"metadata,omitempty"`
}

// SourceConnector The specification of the Kafka MirrorMaker 2 source connector.
type SourceConnector struct {

  // Automatic restart of connector and tasks configuration.
  AutoRestart *AutoRestart `json:"autoRestart,omitempty"`

  // The Kafka Connector configuration. The following properties cannot be set: connector.class, tasks.max.
  Config *Config `json:"config,omitempty"`

  // Whether the connector should be paused. Defaults to false.
  Pause bool `json:"pause,omitempty"`

  // The maximum number of tasks for the Kafka Connector.
  TasksMax int `json:"tasksMax,omitempty"`
}

// Spec The specification of the Kafka MirrorMaker 2 cluster.
type Spec struct {

  // The image of the init container used for initializing the `client.rack`.
  ClientRackInitImage string `json:"clientRackInitImage,omitempty"`

  // Kafka clusters for mirroring.
  Clusters []*ClustersItems `json:"clusters,omitempty"`

  // The cluster alias used for Kafka Connect. The alias must match a cluster in the list at `spec.clusters`.
  ConnectCluster string `json:"connectCluster"`

  // Pass data from Secrets or ConfigMaps to the Kafka Connect pods and use them to configure connectors.
  ExternalConfiguration *ExternalConfiguration `json:"externalConfiguration,omitempty"`

  // The docker image for the pods.
  Image string `json:"image,omitempty"`

  // JMX Options.
  JmxOptions *JmxOptions `json:"jmxOptions,omitempty"`

  // JVM Options for pods.
  JvmOptions *JvmOptions `json:"jvmOptions,omitempty"`

  // Pod liveness checking.
  LivenessProbe *LivenessProbe `json:"livenessProbe,omitempty"`

  // Logging configuration for Kafka Connect.
  Logging *Logging `json:"logging,omitempty"`

  // Metrics configuration.
  MetricsConfig *MetricsConfig `json:"metricsConfig,omitempty"`

  // Configuration of the MirrorMaker 2 connectors.
  Mirrors []*MirrorsItems `json:"mirrors,omitempty"`

  // Configuration of the node label which will be used as the `client.rack` consumer configuration.
  Rack *Rack `json:"rack,omitempty"`

  // Pod readiness checking.
  ReadinessProbe *ReadinessProbe `json:"readinessProbe,omitempty"`

  // The number of pods in the Kafka Connect group. Defaults to `3`.
  Replicas int `json:"replicas,omitempty"`

  // The maximum limits for CPU and memory resources and the requested initial resources.
  Resources *Resources `json:"resources,omitempty"`

  // Template for Kafka Connect and Kafka Mirror Maker 2 resources. The template allows users to specify how the `Deployment`, `Pods` and `Service` are generated.
  Template *Template `json:"template,omitempty"`

  // The configuration of tracing in Kafka Connect.
  Tracing *Tracing `json:"tracing,omitempty"`

  // The Kafka Connect version. Defaults to {DefaultKafkaVersion}. Consult the user documentation to understand the process required to upgrade or downgrade the version.
  Version string `json:"version,omitempty"`
}

// Status The status of the Kafka MirrorMaker 2 cluster.
type Status struct {

  // List of MirrorMaker 2 connector auto restart statuses.
  AutoRestartStatuses []*AutoRestartStatusesItems `json:"autoRestartStatuses,omitempty"`

  // List of status conditions.
  Conditions []*ConditionsItems `json:"conditions,omitempty"`

  // The list of connector plugins available in this Kafka Connect deployment.
  ConnectorPlugins []*ConnectorPluginsItems `json:"connectorPlugins,omitempty"`

  // List of MirrorMaker 2 connector statuses, as reported by the Kafka Connect REST API.
  Connectors []*ConnectorsItems `json:"connectors,omitempty"`

  // Label selector for pods providing this resource.
  LabelSelector string `json:"labelSelector,omitempty"`

  // The generation of the CRD that was last reconciled by the operator.
  ObservedGeneration int `json:"observedGeneration,omitempty"`

  // The current number of pods being used to provide this resource.
  Replicas int `json:"replicas,omitempty"`

  // The URL of the REST API endpoint for managing and monitoring Kafka Connect connectors.
  Url string `json:"url,omitempty"`
}

// SysctlsItems 
type SysctlsItems struct {
  Name string `json:"name,omitempty"`
  Value string `json:"value,omitempty"`
}

// Template Template for Kafka Connect and Kafka Mirror Maker 2 resources. The template allows users to specify how the `Deployment`, `Pods` and `Service` are generated.
type Template struct {

  // Template for Kafka Connect API `Service`.
  ApiService *ApiService `json:"apiService,omitempty"`

  // Template for the Kafka Connect BuildConfig used to build new container images. The BuildConfig is used only on OpenShift.
  BuildConfig *BuildConfig `json:"buildConfig,omitempty"`

  // Template for the Kafka Connect Build container. The build container is used only on Kubernetes.
  BuildContainer *BuildContainer `json:"buildContainer,omitempty"`

  // Template for Kafka Connect Build `Pods`. The build pod is used only on Kubernetes.
  BuildPod *BuildPod `json:"buildPod,omitempty"`

  // Template for the Kafka Connect Build service account.
  BuildServiceAccount *BuildServiceAccount `json:"buildServiceAccount,omitempty"`

  // Template for the Kafka Connect ClusterRoleBinding.
  ClusterRoleBinding *ClusterRoleBinding `json:"clusterRoleBinding,omitempty"`

  // Template for the Kafka Connect container.
  ConnectContainer *ConnectContainer `json:"connectContainer,omitempty"`

  // Template for Kafka Connect `Deployment`.
  Deployment *Deployment `json:"deployment,omitempty"`

  // Template for Kafka Connect headless `Service`.
  HeadlessService *HeadlessService `json:"headlessService,omitempty"`

  // Template for the Kafka init container.
  InitContainer *InitContainer `json:"initContainer,omitempty"`

  // Template for Secret of the Kafka Connect Cluster JMX authentication.
  JmxSecret *JmxSecret `json:"jmxSecret,omitempty"`

  // Template for Kafka Connect `Pods`.
  Pod *Pod `json:"pod,omitempty"`

  // Template for Kafka Connect `PodDisruptionBudget`.
  PodDisruptionBudget *PodDisruptionBudget `json:"podDisruptionBudget,omitempty"`

  // Template for Kafka Connect `StrimziPodSet` resource.
  PodSet *PodSet `json:"podSet,omitempty"`

  // Template for the Kafka Connect service account.
  ServiceAccount *ServiceAccount `json:"serviceAccount,omitempty"`
}

// Tls TLS configuration for connecting MirrorMaker 2 connectors to a cluster.
type Tls struct {

  // Trusted certificates for TLS connection.
  TrustedCertificates []*TrustedCertificatesItems `json:"trustedCertificates,omitempty"`
}

// TlsTrustedCertificatesItems 
type TlsTrustedCertificatesItems struct {

  // The name of the file certificate in the Secret.
  Certificate string `json:"certificate"`

  // The name of the Secret containing the certificate.
  SecretName string `json:"secretName"`
}

// TolerationsItems 
type TolerationsItems struct {
  Effect string `json:"effect,omitempty"`
  Key string `json:"key,omitempty"`
  Operator string `json:"operator,omitempty"`
  TolerationSeconds int `json:"tolerationSeconds,omitempty"`
  Value string `json:"value,omitempty"`
}

// TopologySpreadConstraintsItems 
type TopologySpreadConstraintsItems struct {
  LabelSelector *LabelSelector `json:"labelSelector,omitempty"`
  MatchLabelKeys []string `json:"matchLabelKeys,omitempty"`
  MaxSkew int `json:"maxSkew,omitempty"`
  MinDomains int `json:"minDomains,omitempty"`
  NodeAffinityPolicy string `json:"nodeAffinityPolicy,omitempty"`
  NodeTaintsPolicy string `json:"nodeTaintsPolicy,omitempty"`
  TopologyKey string `json:"topologyKey,omitempty"`
  WhenUnsatisfiable string `json:"whenUnsatisfiable,omitempty"`
}

// Tracing The configuration of tracing in Kafka Connect.
type Tracing struct {

  // Type of the tracing used. Currently the only supported types are `jaeger` for OpenTracing (Jaeger) tracing and `opentelemetry` for OpenTelemetry tracing. The OpenTracing (Jaeger) tracing is deprecated.
  Type string `json:"type"`
}

// TrustedCertificatesItems 
type TrustedCertificatesItems struct {

  // The name of the file certificate in the Secret.
  Certificate string `json:"certificate"`

  // The name of the Secret containing the certificate.
  SecretName string `json:"secretName"`
}

// ValueFrom Value of the environment variable which will be passed to the Kafka Connect pods. It can be passed either as a reference to Secret or ConfigMap field. The field has to specify exactly one Secret or ConfigMap.
type ValueFrom struct {

  // Reference to a key in a ConfigMap.
  ConfigMapKeyRef *ConfigMapKeyRef `json:"configMapKeyRef,omitempty"`

  // Reference to a key in a Secret.
  SecretKeyRef *SecretKeyRef `json:"secretKeyRef,omitempty"`
}

// VolumesItems 
type VolumesItems struct {

  // Reference to a key in a ConfigMap. Exactly one Secret or ConfigMap has to be specified.
  ConfigMap *ConfigMap `json:"configMap,omitempty"`

  // Name of the volume which will be added to the Kafka Connect pods.
  Name string `json:"name"`

  // Reference to a key in a Secret. Exactly one Secret or ConfigMap has to be specified.
  Secret *Secret `json:"secret,omitempty"`
}

// WindowsOptions 
type WindowsOptions struct {
  GmsaCredentialSpec string `json:"gmsaCredentialSpec,omitempty"`
  GmsaCredentialSpecName string `json:"gmsaCredentialSpecName,omitempty"`
  HostProcess bool `json:"hostProcess,omitempty"`
  RunAsUserName string `json:"runAsUserName,omitempty"`
}

// XX A map of -XX options to the JVM.
type XX struct {
}

func (strct *AccessToken) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Key" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "key" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"key\": ")
	if tmp, err := json.Marshal(strct.Key); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "SecretName" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "secretName" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"secretName\": ")
	if tmp, err := json.Marshal(strct.SecretName); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *AccessToken) UnmarshalJSON(b []byte) error {
    keyReceived := false
    secretNameReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "key":
            if err := json.Unmarshal([]byte(v), &strct.Key); err != nil {
                return err
             }
            keyReceived = true
        case "secretName":
            if err := json.Unmarshal([]byte(v), &strct.SecretName); err != nil {
                return err
             }
            secretNameReceived = true
        }
    }
    // check if key (a required property) was received
    if !keyReceived {
        return errors.New("\"key\" is required but was not present")
    }
    // check if secretName (a required property) was received
    if !secretNameReceived {
        return errors.New("\"secretName\" is required but was not present")
    }
    return nil
}

func (strct *Authentication) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Type" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "type" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"type\": ")
	if tmp, err := json.Marshal(strct.Type); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Authentication) UnmarshalJSON(b []byte) error {
    typeReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "type":
            if err := json.Unmarshal([]byte(v), &strct.Type); err != nil {
                return err
             }
            typeReceived = true
        }
    }
    // check if type (a required property) was received
    if !typeReceived {
        return errors.New("\"type\" is required but was not present")
    }
    return nil
}

func (strct *CertificateAndKey) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Certificate" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "certificate" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"certificate\": ")
	if tmp, err := json.Marshal(strct.Certificate); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Key" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "key" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"key\": ")
	if tmp, err := json.Marshal(strct.Key); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "SecretName" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "secretName" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"secretName\": ")
	if tmp, err := json.Marshal(strct.SecretName); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *CertificateAndKey) UnmarshalJSON(b []byte) error {
    certificateReceived := false
    keyReceived := false
    secretNameReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "certificate":
            if err := json.Unmarshal([]byte(v), &strct.Certificate); err != nil {
                return err
             }
            certificateReceived = true
        case "key":
            if err := json.Unmarshal([]byte(v), &strct.Key); err != nil {
                return err
             }
            keyReceived = true
        case "secretName":
            if err := json.Unmarshal([]byte(v), &strct.SecretName); err != nil {
                return err
             }
            secretNameReceived = true
        }
    }
    // check if certificate (a required property) was received
    if !certificateReceived {
        return errors.New("\"certificate\" is required but was not present")
    }
    // check if key (a required property) was received
    if !keyReceived {
        return errors.New("\"key\" is required but was not present")
    }
    // check if secretName (a required property) was received
    if !secretNameReceived {
        return errors.New("\"secretName\" is required but was not present")
    }
    return nil
}

func (strct *ClientSecret) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Key" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "key" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"key\": ")
	if tmp, err := json.Marshal(strct.Key); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "SecretName" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "secretName" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"secretName\": ")
	if tmp, err := json.Marshal(strct.SecretName); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *ClientSecret) UnmarshalJSON(b []byte) error {
    keyReceived := false
    secretNameReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "key":
            if err := json.Unmarshal([]byte(v), &strct.Key); err != nil {
                return err
             }
            keyReceived = true
        case "secretName":
            if err := json.Unmarshal([]byte(v), &strct.SecretName); err != nil {
                return err
             }
            secretNameReceived = true
        }
    }
    // check if key (a required property) was received
    if !keyReceived {
        return errors.New("\"key\" is required but was not present")
    }
    // check if secretName (a required property) was received
    if !secretNameReceived {
        return errors.New("\"secretName\" is required but was not present")
    }
    return nil
}

func (strct *ClustersItems) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Alias" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "alias" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"alias\": ")
	if tmp, err := json.Marshal(strct.Alias); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "authentication" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"authentication\": ")
	if tmp, err := json.Marshal(strct.Authentication); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "BootstrapServers" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "bootstrapServers" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"bootstrapServers\": ")
	if tmp, err := json.Marshal(strct.BootstrapServers); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "config" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"config\": ")
	if tmp, err := json.Marshal(strct.Config); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "tls" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"tls\": ")
	if tmp, err := json.Marshal(strct.Tls); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *ClustersItems) UnmarshalJSON(b []byte) error {
    aliasReceived := false
    bootstrapServersReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "alias":
            if err := json.Unmarshal([]byte(v), &strct.Alias); err != nil {
                return err
             }
            aliasReceived = true
        case "authentication":
            if err := json.Unmarshal([]byte(v), &strct.Authentication); err != nil {
                return err
             }
        case "bootstrapServers":
            if err := json.Unmarshal([]byte(v), &strct.BootstrapServers); err != nil {
                return err
             }
            bootstrapServersReceived = true
        case "config":
            if err := json.Unmarshal([]byte(v), &strct.Config); err != nil {
                return err
             }
        case "tls":
            if err := json.Unmarshal([]byte(v), &strct.Tls); err != nil {
                return err
             }
        }
    }
    // check if alias (a required property) was received
    if !aliasReceived {
        return errors.New("\"alias\" is required but was not present")
    }
    // check if bootstrapServers (a required property) was received
    if !bootstrapServersReceived {
        return errors.New("\"bootstrapServers\" is required but was not present")
    }
    return nil
}

func (strct *EnvItems) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Name" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "name" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"name\": ")
	if tmp, err := json.Marshal(strct.Name); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "ValueFrom" field is required
    if strct.ValueFrom == nil {
        return nil, errors.New("valueFrom is a required field")
    }
    // Marshal the "valueFrom" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"valueFrom\": ")
	if tmp, err := json.Marshal(strct.ValueFrom); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *EnvItems) UnmarshalJSON(b []byte) error {
    nameReceived := false
    valueFromReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "name":
            if err := json.Unmarshal([]byte(v), &strct.Name); err != nil {
                return err
             }
            nameReceived = true
        case "valueFrom":
            if err := json.Unmarshal([]byte(v), &strct.ValueFrom); err != nil {
                return err
             }
            valueFromReceived = true
        }
    }
    // check if name (a required property) was received
    if !nameReceived {
        return errors.New("\"name\" is required but was not present")
    }
    // check if valueFrom (a required property) was received
    if !valueFromReceived {
        return errors.New("\"valueFrom\" is required but was not present")
    }
    return nil
}

func (strct *Logging) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "loggers" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"loggers\": ")
	if tmp, err := json.Marshal(strct.Loggers); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Type" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "type" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"type\": ")
	if tmp, err := json.Marshal(strct.Type); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "valueFrom" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"valueFrom\": ")
	if tmp, err := json.Marshal(strct.ValueFrom); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Logging) UnmarshalJSON(b []byte) error {
    typeReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "loggers":
            if err := json.Unmarshal([]byte(v), &strct.Loggers); err != nil {
                return err
             }
        case "type":
            if err := json.Unmarshal([]byte(v), &strct.Type); err != nil {
                return err
             }
            typeReceived = true
        case "valueFrom":
            if err := json.Unmarshal([]byte(v), &strct.ValueFrom); err != nil {
                return err
             }
        }
    }
    // check if type (a required property) was received
    if !typeReceived {
        return errors.New("\"type\" is required but was not present")
    }
    return nil
}

func (strct *MetricsConfig) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Type" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "type" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"type\": ")
	if tmp, err := json.Marshal(strct.Type); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "ValueFrom" field is required
    if strct.ValueFrom == nil {
        return nil, errors.New("valueFrom is a required field")
    }
    // Marshal the "valueFrom" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"valueFrom\": ")
	if tmp, err := json.Marshal(strct.ValueFrom); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *MetricsConfig) UnmarshalJSON(b []byte) error {
    typeReceived := false
    valueFromReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "type":
            if err := json.Unmarshal([]byte(v), &strct.Type); err != nil {
                return err
             }
            typeReceived = true
        case "valueFrom":
            if err := json.Unmarshal([]byte(v), &strct.ValueFrom); err != nil {
                return err
             }
            valueFromReceived = true
        }
    }
    // check if type (a required property) was received
    if !typeReceived {
        return errors.New("\"type\" is required but was not present")
    }
    // check if valueFrom (a required property) was received
    if !valueFromReceived {
        return errors.New("\"valueFrom\" is required but was not present")
    }
    return nil
}

func (strct *MirrorsItems) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "checkpointConnector" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"checkpointConnector\": ")
	if tmp, err := json.Marshal(strct.CheckpointConnector); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "groupsBlacklistPattern" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"groupsBlacklistPattern\": ")
	if tmp, err := json.Marshal(strct.GroupsBlacklistPattern); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "groupsExcludePattern" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"groupsExcludePattern\": ")
	if tmp, err := json.Marshal(strct.GroupsExcludePattern); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "groupsPattern" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"groupsPattern\": ")
	if tmp, err := json.Marshal(strct.GroupsPattern); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "heartbeatConnector" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"heartbeatConnector\": ")
	if tmp, err := json.Marshal(strct.HeartbeatConnector); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "SourceCluster" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "sourceCluster" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"sourceCluster\": ")
	if tmp, err := json.Marshal(strct.SourceCluster); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "sourceConnector" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"sourceConnector\": ")
	if tmp, err := json.Marshal(strct.SourceConnector); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "TargetCluster" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "targetCluster" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"targetCluster\": ")
	if tmp, err := json.Marshal(strct.TargetCluster); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "topicsBlacklistPattern" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"topicsBlacklistPattern\": ")
	if tmp, err := json.Marshal(strct.TopicsBlacklistPattern); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "topicsExcludePattern" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"topicsExcludePattern\": ")
	if tmp, err := json.Marshal(strct.TopicsExcludePattern); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "topicsPattern" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"topicsPattern\": ")
	if tmp, err := json.Marshal(strct.TopicsPattern); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *MirrorsItems) UnmarshalJSON(b []byte) error {
    sourceClusterReceived := false
    targetClusterReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "checkpointConnector":
            if err := json.Unmarshal([]byte(v), &strct.CheckpointConnector); err != nil {
                return err
             }
        case "groupsBlacklistPattern":
            if err := json.Unmarshal([]byte(v), &strct.GroupsBlacklistPattern); err != nil {
                return err
             }
        case "groupsExcludePattern":
            if err := json.Unmarshal([]byte(v), &strct.GroupsExcludePattern); err != nil {
                return err
             }
        case "groupsPattern":
            if err := json.Unmarshal([]byte(v), &strct.GroupsPattern); err != nil {
                return err
             }
        case "heartbeatConnector":
            if err := json.Unmarshal([]byte(v), &strct.HeartbeatConnector); err != nil {
                return err
             }
        case "sourceCluster":
            if err := json.Unmarshal([]byte(v), &strct.SourceCluster); err != nil {
                return err
             }
            sourceClusterReceived = true
        case "sourceConnector":
            if err := json.Unmarshal([]byte(v), &strct.SourceConnector); err != nil {
                return err
             }
        case "targetCluster":
            if err := json.Unmarshal([]byte(v), &strct.TargetCluster); err != nil {
                return err
             }
            targetClusterReceived = true
        case "topicsBlacklistPattern":
            if err := json.Unmarshal([]byte(v), &strct.TopicsBlacklistPattern); err != nil {
                return err
             }
        case "topicsExcludePattern":
            if err := json.Unmarshal([]byte(v), &strct.TopicsExcludePattern); err != nil {
                return err
             }
        case "topicsPattern":
            if err := json.Unmarshal([]byte(v), &strct.TopicsPattern); err != nil {
                return err
             }
        }
    }
    // check if sourceCluster (a required property) was received
    if !sourceClusterReceived {
        return errors.New("\"sourceCluster\" is required but was not present")
    }
    // check if targetCluster (a required property) was received
    if !targetClusterReceived {
        return errors.New("\"targetCluster\" is required but was not present")
    }
    return nil
}

func (strct *PasswordSecret) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Password" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "password" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"password\": ")
	if tmp, err := json.Marshal(strct.Password); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "SecretName" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "secretName" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"secretName\": ")
	if tmp, err := json.Marshal(strct.SecretName); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *PasswordSecret) UnmarshalJSON(b []byte) error {
    passwordReceived := false
    secretNameReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "password":
            if err := json.Unmarshal([]byte(v), &strct.Password); err != nil {
                return err
             }
            passwordReceived = true
        case "secretName":
            if err := json.Unmarshal([]byte(v), &strct.SecretName); err != nil {
                return err
             }
            secretNameReceived = true
        }
    }
    // check if password (a required property) was received
    if !passwordReceived {
        return errors.New("\"password\" is required but was not present")
    }
    // check if secretName (a required property) was received
    if !secretNameReceived {
        return errors.New("\"secretName\" is required but was not present")
    }
    return nil
}

func (strct *Rack) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "TopologyKey" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "topologyKey" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"topologyKey\": ")
	if tmp, err := json.Marshal(strct.TopologyKey); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Rack) UnmarshalJSON(b []byte) error {
    topologyKeyReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "topologyKey":
            if err := json.Unmarshal([]byte(v), &strct.TopologyKey); err != nil {
                return err
             }
            topologyKeyReceived = true
        }
    }
    // check if topologyKey (a required property) was received
    if !topologyKeyReceived {
        return errors.New("\"topologyKey\" is required but was not present")
    }
    return nil
}

func (strct *RefreshToken) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Key" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "key" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"key\": ")
	if tmp, err := json.Marshal(strct.Key); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "SecretName" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "secretName" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"secretName\": ")
	if tmp, err := json.Marshal(strct.SecretName); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *RefreshToken) UnmarshalJSON(b []byte) error {
    keyReceived := false
    secretNameReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "key":
            if err := json.Unmarshal([]byte(v), &strct.Key); err != nil {
                return err
             }
            keyReceived = true
        case "secretName":
            if err := json.Unmarshal([]byte(v), &strct.SecretName); err != nil {
                return err
             }
            secretNameReceived = true
        }
    }
    // check if key (a required property) was received
    if !keyReceived {
        return errors.New("\"key\" is required but was not present")
    }
    // check if secretName (a required property) was received
    if !secretNameReceived {
        return errors.New("\"secretName\" is required but was not present")
    }
    return nil
}

func (strct *Spec) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "clientRackInitImage" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"clientRackInitImage\": ")
	if tmp, err := json.Marshal(strct.ClientRackInitImage); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "clusters" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"clusters\": ")
	if tmp, err := json.Marshal(strct.Clusters); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "ConnectCluster" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "connectCluster" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"connectCluster\": ")
	if tmp, err := json.Marshal(strct.ConnectCluster); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "externalConfiguration" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"externalConfiguration\": ")
	if tmp, err := json.Marshal(strct.ExternalConfiguration); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "image" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"image\": ")
	if tmp, err := json.Marshal(strct.Image); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "jmxOptions" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"jmxOptions\": ")
	if tmp, err := json.Marshal(strct.JmxOptions); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "jvmOptions" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"jvmOptions\": ")
	if tmp, err := json.Marshal(strct.JvmOptions); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "livenessProbe" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"livenessProbe\": ")
	if tmp, err := json.Marshal(strct.LivenessProbe); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "logging" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"logging\": ")
	if tmp, err := json.Marshal(strct.Logging); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "metricsConfig" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"metricsConfig\": ")
	if tmp, err := json.Marshal(strct.MetricsConfig); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "mirrors" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"mirrors\": ")
	if tmp, err := json.Marshal(strct.Mirrors); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "rack" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"rack\": ")
	if tmp, err := json.Marshal(strct.Rack); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "readinessProbe" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"readinessProbe\": ")
	if tmp, err := json.Marshal(strct.ReadinessProbe); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "replicas" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"replicas\": ")
	if tmp, err := json.Marshal(strct.Replicas); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "resources" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"resources\": ")
	if tmp, err := json.Marshal(strct.Resources); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "template" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"template\": ")
	if tmp, err := json.Marshal(strct.Template); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "tracing" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"tracing\": ")
	if tmp, err := json.Marshal(strct.Tracing); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "version" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"version\": ")
	if tmp, err := json.Marshal(strct.Version); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Spec) UnmarshalJSON(b []byte) error {
    connectClusterReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "clientRackInitImage":
            if err := json.Unmarshal([]byte(v), &strct.ClientRackInitImage); err != nil {
                return err
             }
        case "clusters":
            if err := json.Unmarshal([]byte(v), &strct.Clusters); err != nil {
                return err
             }
        case "connectCluster":
            if err := json.Unmarshal([]byte(v), &strct.ConnectCluster); err != nil {
                return err
             }
            connectClusterReceived = true
        case "externalConfiguration":
            if err := json.Unmarshal([]byte(v), &strct.ExternalConfiguration); err != nil {
                return err
             }
        case "image":
            if err := json.Unmarshal([]byte(v), &strct.Image); err != nil {
                return err
             }
        case "jmxOptions":
            if err := json.Unmarshal([]byte(v), &strct.JmxOptions); err != nil {
                return err
             }
        case "jvmOptions":
            if err := json.Unmarshal([]byte(v), &strct.JvmOptions); err != nil {
                return err
             }
        case "livenessProbe":
            if err := json.Unmarshal([]byte(v), &strct.LivenessProbe); err != nil {
                return err
             }
        case "logging":
            if err := json.Unmarshal([]byte(v), &strct.Logging); err != nil {
                return err
             }
        case "metricsConfig":
            if err := json.Unmarshal([]byte(v), &strct.MetricsConfig); err != nil {
                return err
             }
        case "mirrors":
            if err := json.Unmarshal([]byte(v), &strct.Mirrors); err != nil {
                return err
             }
        case "rack":
            if err := json.Unmarshal([]byte(v), &strct.Rack); err != nil {
                return err
             }
        case "readinessProbe":
            if err := json.Unmarshal([]byte(v), &strct.ReadinessProbe); err != nil {
                return err
             }
        case "replicas":
            if err := json.Unmarshal([]byte(v), &strct.Replicas); err != nil {
                return err
             }
        case "resources":
            if err := json.Unmarshal([]byte(v), &strct.Resources); err != nil {
                return err
             }
        case "template":
            if err := json.Unmarshal([]byte(v), &strct.Template); err != nil {
                return err
             }
        case "tracing":
            if err := json.Unmarshal([]byte(v), &strct.Tracing); err != nil {
                return err
             }
        case "version":
            if err := json.Unmarshal([]byte(v), &strct.Version); err != nil {
                return err
             }
        }
    }
    // check if connectCluster (a required property) was received
    if !connectClusterReceived {
        return errors.New("\"connectCluster\" is required but was not present")
    }
    return nil
}

func (strct *TlsTrustedCertificatesItems) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Certificate" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "certificate" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"certificate\": ")
	if tmp, err := json.Marshal(strct.Certificate); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "SecretName" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "secretName" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"secretName\": ")
	if tmp, err := json.Marshal(strct.SecretName); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *TlsTrustedCertificatesItems) UnmarshalJSON(b []byte) error {
    certificateReceived := false
    secretNameReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "certificate":
            if err := json.Unmarshal([]byte(v), &strct.Certificate); err != nil {
                return err
             }
            certificateReceived = true
        case "secretName":
            if err := json.Unmarshal([]byte(v), &strct.SecretName); err != nil {
                return err
             }
            secretNameReceived = true
        }
    }
    // check if certificate (a required property) was received
    if !certificateReceived {
        return errors.New("\"certificate\" is required but was not present")
    }
    // check if secretName (a required property) was received
    if !secretNameReceived {
        return errors.New("\"secretName\" is required but was not present")
    }
    return nil
}

func (strct *Tracing) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Type" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "type" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"type\": ")
	if tmp, err := json.Marshal(strct.Type); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Tracing) UnmarshalJSON(b []byte) error {
    typeReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "type":
            if err := json.Unmarshal([]byte(v), &strct.Type); err != nil {
                return err
             }
            typeReceived = true
        }
    }
    // check if type (a required property) was received
    if !typeReceived {
        return errors.New("\"type\" is required but was not present")
    }
    return nil
}

func (strct *TrustedCertificatesItems) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Certificate" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "certificate" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"certificate\": ")
	if tmp, err := json.Marshal(strct.Certificate); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "SecretName" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "secretName" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"secretName\": ")
	if tmp, err := json.Marshal(strct.SecretName); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *TrustedCertificatesItems) UnmarshalJSON(b []byte) error {
    certificateReceived := false
    secretNameReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "certificate":
            if err := json.Unmarshal([]byte(v), &strct.Certificate); err != nil {
                return err
             }
            certificateReceived = true
        case "secretName":
            if err := json.Unmarshal([]byte(v), &strct.SecretName); err != nil {
                return err
             }
            secretNameReceived = true
        }
    }
    // check if certificate (a required property) was received
    if !certificateReceived {
        return errors.New("\"certificate\" is required but was not present")
    }
    // check if secretName (a required property) was received
    if !secretNameReceived {
        return errors.New("\"secretName\" is required but was not present")
    }
    return nil
}

func (strct *VolumesItems) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "configMap" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"configMap\": ")
	if tmp, err := json.Marshal(strct.ConfigMap); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Name" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "name" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"name\": ")
	if tmp, err := json.Marshal(strct.Name); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "secret" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"secret\": ")
	if tmp, err := json.Marshal(strct.Secret); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *VolumesItems) UnmarshalJSON(b []byte) error {
    nameReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "configMap":
            if err := json.Unmarshal([]byte(v), &strct.ConfigMap); err != nil {
                return err
             }
        case "name":
            if err := json.Unmarshal([]byte(v), &strct.Name); err != nil {
                return err
             }
            nameReceived = true
        case "secret":
            if err := json.Unmarshal([]byte(v), &strct.Secret); err != nil {
                return err
             }
        }
    }
    // check if name (a required property) was received
    if !nameReceived {
        return errors.New("\"name\" is required but was not present")
    }
    return nil
}
